server:
  port: 9003
spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://localhost:3309/inventorydb?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
