server:
  port: 9004
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3310/orderdb?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
