server:
  port: 9002
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3308/productdb?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
